/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconMdiEyeOutline: typeof import('~icons/mdi/eye-outline')['default']
    IMdiAccount: typeof import('~icons/mdi/account')['default']
    IMdiEyeOutline: typeof import('~icons/mdi/eye-outline')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
